### ISSUE TITLE
Unable to push compressed assets

### ISSUE THREAD

**Issue by chrstntdd** [devinivy/underdog#11]
`Hapi: v17.2.0`
`Inert: v5.1.0`
`Underdog: v2.0.1`

Unless I am going about this all wrong, I cannot get `h.push()` to push back `.gz` assets for the array of paths provided as the second argument. Is this supported currently?

From what I understand, Hapi handles compression out of the box, but in my use case I have gzipped the assets myself and want to respond to requests for compressible assets (js, css, etc..) with their compressed counterparts. 

```js
// This works, but the assets returned are uncompressed
  const index = readFileSync(join(__dirname, 'public/index.html')).toString();
  server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
      const response = h.response(index);
      h.push(response, ['/app.js', '/pure.css', '/assets/hero-bg.jpg']);

      return response;
    }
  });
```
---

```js
/*This is not supported. The compressed resources are not pushed to the client,
  but instead the client discovers the assets after parsing through the `index .html` 
  and the automatically compressed assets are returned */
  const index = readFileSync(join(__dirname, 'public/index.html')).toString();
  server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
      const response = h.response(index);
      h.push(response, ['/app.js.gz', '/pure.css.gz', '/assets/hero-bg.jpg']);

      return response;
    }
  });
```

This is a simplified version of my config for clarity:

```js
(async () => {
  const listener = h2.createSecureServer({
    key: readFileSync(join(__dirname, '/keys/key.pem'), 'UTF-8'),
    cert: readFileSync(join(__dirname, '/keys/server.crt'), 'UTF-8')
  });

  const port = configs.port;
  const server = new Hapi.Server({
    port,
    listener,
    tls: true,
    routes: {
      files: {
        relativeTo: join(__dirname, 'public')
      }
    }
  });

  await server.register([
    Inert,
    ...
    Underdog
  ]);

  /* FOR SERVING FRONT END ASSETS FOR ALL REQUESTS. */
  server.route({
    method: 'GET',
    path: '/{param*}',
    handler: {
      directory: {
        path: '.',
        index: true,
        redirectToSlash: true
      }
    }
  });

  /* ~Other route handlers~ */
})()
```

**Comment by devinivy** [comment]
Hey!  So, there are a couple things going on it.  As far as I know, simply pushing down gzipped versions of files with the `.gz` suffix does not cause the browser to use them rather than whatever resource is referenced in your `<link>` (for CSS) or `<script>` (for JS) tag.  The actual URI has to match.

If your script tag says `<script src="/app.js">` then you need to push the path `/app.js` rather than `/app.js.gz`.  The browser wont infer that those are the same resource, and that one is just gzipped.

Luckily between inert and underdog, you should be able to do what you're aiming for!  First, tell inert to lookup compressed versions of files when appropriate using the `lookupCompressed: true` handler option.  Whenever a file is requested and `gzip` is an acceptable encoding, inert will serve the `.gz` version of the file and set appropriate headers to tell the browser that it's gzipped.  Underdog just needs to indicate that gzip is an acceptable encoding by sending the push-request with the proper `accept-encoding` header.  Here's what your routes might look like,

```js
  const index = readFileSync(join(__dirname, 'public/index.html')).toString();
  server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
      const response = h.response(index);
      h.push(response, ['/app.js', '/pure.css', '/assets/hero-bg.jpg'], {
        'accept-encoding': 'gzip' // Tell inert that gzip is an acceptable compression to use
      });

      return response;
    }
  });

  server.route({
    method: 'GET',
    path: '/{param*}',
    handler: {
      directory: {
        path: '.',
        index: true,
        redirectToSlash: true,
        lookupCompressed: true // Lookup .gz files when appropriate
      }
    }
  });

**Comment by chrstntdd** [comment]
Ah! Yes. That header was the missing piece of the puzzle. Thank you very much!
